ALTER TABLE ManutencaoVeiculo
ADD COLUMN Categoria VARCHAR(80) NULL,
ADD COLUMN DataAgendamento DATETIME NULL,
ADD COLUMN DataConclusao DATETIME NULL,
ADD COLUMN GarantiaAte DATETIME NULL,
ADD COLUMN LocalExecucaoServico VARCHAR(150) NULL,
ADD COLUMN Fornecedor VARCHAR(150) NULL,
ADD COLUMN ResponsavelServico VARCHAR(120) NULL,
ADD COLUMN ContatoFornecedor VARCHAR(80) NULL,
ADD COLUMN NumeroDocumento VARCHAR(80) NULL,
ADD COLUMN CustoPrevisto DECIMAL(18,2) NULL,
ADD COLUMN ValorMaximoAutorizado DECIMAL(18,2) NULL,
ADD COLUMN ValorTotalGasto DECIMAL(18,2) NULL;
